### ISSUE TITLE
Make calculations.js pure functions

### ISSUE THREAD

**Issue by okwme** [okwme/anybody-problem#35]
I like this step to break the file down. I would recommend we pull as many functions as we can out of the `Anybody` class and just import/call them. I think most of the `Calculations` do not have any side effects that modify `this`, they are just reading data from `this` that could be passed in as params. So most can just be exported functions outside of Anybody. This will also allow tree shaking, easy identification of unused code, and less chance of leaks from context binding.

_Originally posted by @psugihara in https://github.com/okwme/anybody-problem/pull/30#discussion_r1516665700_

**Comment by psugihara** [comment]
we clean enough 🧹 . can revisit later if this is an issue.
