### ISSUE TITLE
iOS errors when unpausing

### ISSUE THREAD

**Issue by psugihara** [okwme/anybody-problem#41]
Seeing this in chrome and safari via ngrok. @okwme you see something like this too?

<img width="999" alt="Screenshot 2024-03-12 at 12 11 47 PM" src="https://github.com/okwme/anybody-problem/assets/282016/cd07b1b4-c6f1-4238-a081-d28ffcf23e92">

![IMG_29C2AFF89968-1](https://github.com/okwme/anybody-problem/assets/282016/4f5f1f41-5de3-4ec6-8486-6897bf89b9b1)

**Comment by okwme** [comment]
Haven't tried in ngrok, looks like it's from q5. What page is being served?

**Comment by okwme** [comment]
Maybe requires a polyfill?

**Comment by okwme** [comment]
I also see it without ngrok. You should be able to visit with mobile on the same network as your computer using the ip address in console after running `yarn dev`
