### ISSUE TITLE
Add face variations

### ISSUE THREAD

**Issue by okwme** [okwme/anybody-problem#81]
## Add face variations
There should be variations of the faces in the google drive folder of anybody assets. The faces should swap out so that when starLvl is less than 1/3 of totalStarLvl the "sleepy" face is used. When starLvl is less than 2/3 but greater than 1/3 of totalStarLvl the "normal" face is used. When starLvl is above 2/3 totalStarLvl then the "ecstatic" face is used.

**Comment by okwme** [comment]
@psugihara These are all in the google drive now!

basic idea above still make sense but i really love seeing the transition between them so thought we could try some methods to increase the opportunities to see that switch.

first idea would be that when they get hit during an active game, they rotate through all three of their expressions until the game is over.

second idea would be that when they get hit during an active game, they upgrade to next level regardless of where they actually are in the 1/3, 2/3, 3/3 progression (this wouldn't work for 3/3 since there's no level higher of course). Then the faces reset to their correct starting points when the next level starts.

third idea is to make the faces change actually based on time left in the game, so they all start out sleepy but get more and more excited as the end comes near (only a little worried with this option that you miss some of the expressions if they're all happening simultaneously)


Would you wanna try out some of those options while working on this issue and share results?

**Comment by okwme** [comment]
![telegram-cloud-photo-size-1-4929395968223325108-y](https://github.com/okwme/anybody-problem/assets/964052/c49679e4-8d52-44fe-bcf2-e54e94fafd68)

**Comment by psugihara** [comment]
beautiful! adding them now

**Comment by psugihara** [comment]
i'll try the variations you mention
