### ISSUE TITLE
New Game / Play Again

### ISSUE THREAD

**Issue by okwme** [okwme/anybody-problem#91]
ensure state is refreshed, and an event is emitted so a front end can also refresh state. Probably should keep `bodyData` as source of play if game is lost. If game is won, maybe wait for new `bodyData`. Similarly add a updateState method, that the frontend could trigger, when there's a newer version of the game to play (like after a body was added). That way we can avoid these hard refreshes.

**Comment by psugihara** [comment]
gonna try this
